.TH mhuxd 8 "May 2013" "" "Router Daemon for microHam Keyers"

.SH NAME
mhuxd \- Router Daemon for microHam keyers

..SH SYNOPSIS
.B mhuxd
.RI [ options ]
.br

.SH DESCRIPTION
\fBMhuxd\fP
is a device router for microHam keyers. Currently it runs on the
Linux operating system only. Supported microHam keyers are:

.PP 
    micro KEYER
    micro KEYER II
    DIGI KEYER
    DIGI KEYER II
    MK2R & MK2R+
    CW KEYER

\fBMhuxd\fP provides a web interface. It allows to perform keyer 
configuration changes including Winkey configuration. Once mhuxd 
is running the web interfaces can be accessed at:

      \fBhttp://localhost:5052\fP

This can be changed by the -w option.

mhuxd automatically discovers any supported microHam devices which are connected to an USB port. The daemon
can control multiple microHam devices simultaneously.


Similar to the microHam device router mhuxd can create virtual serial ports.
This allows ham radio applications like CQRLOG or Fldigi to send rig commands
or utilize the K1EL Winkey chip. These ports can be created using the web
interface.


.SH OPTIONS

.TP
\fB\-h\fR
Prints a list of available options

.TP
\fB\-w\fR \fI<interface:port>\fR

interface and port of the webserver
(default: localhost:5052)

.TP
\fB\-b\fR
run in background, log to logfile


.SH AUTHOR
Written by Matthias Moeller, DJ5QV

.SH "REPORTING BUGS"
Report mhuxd bugs to dj5qv@maxec.de

