#!/bin/sh -e

if ! ([ "$1" = "configure" ] || [ "$1" = "reconfigure" ]); then
  exit 0
fi

MHUXD=mhuxd

[ -d /var/run/mhuxd ] || mkdir -p /var/run/mhuxd

adduser --system --quiet --home /var/run/$MHUXD --no-create-home  \
        --group $MHUXD 

chown $MHUXD:$MHUXD /var/run/mhuxd


# udev may have ignored our new rule if the group mhuxd was not
# existing yet.
udevadm control --reload-rules

# Automatically added by dh_installinit
if [ -x "/etc/init.d/mhuxd" ]; then
	update-rc.d mhuxd defaults >/dev/null
	invoke-rc.d mhuxd start || exit $?
fi
# End automatically added section


