#!/bin/sh -e

if ! ([ "$1" = "configure" ] || [ "$1" = "reconfigure" ]); then
  exit 0
fi

MHUXD=mhuxd

[ -d /var/run/mhuxd ] || mkdir -p /var/run/mhuxd

adduser --system --quiet --home /var/run/$MHUXD --no-create-home  \
        --group $MHUXD 

chown $MHUXD:$MHUXD /var/run/mhuxd

# udev may have ignored our new rule as group mhuxd may not have 
# existed yet.

udevadm control --reload-rules

#DEBHELPER#

