#!/bin/sh -e

if ! ([ "$1" = "configure" ] || [ "$1" = "reconfigure" ]); then
  exit 0
fi

MHUXD=mhuxd

adduser --system --quiet --home /nonexistent --no-create-home  \
        --group $MHUXD 

# udev may have ignored our new rule as group mhuxd may not have 
# existed yet.

udevadm control --reload-rules

#DEBHELPER#

