[#installation]
== Installation

=== Installation from package
Binary packages for Debian and Debian based distributions (e.g. Ubuntu, Mint) are
available. The home page http://mhuxd.dj5qv.de provides up-to-date installation steps.

=== Compiling from Source

==== Prerequisites

To compile mhuxd you need a C compiler, `pkg-config` and the development packages for:

* libudev (`libudev-dev`)
* libfuse (`libfuse-dev`)
* libev (`libev-dev`)
* libjansson (`libjansson-dev`) – JSON configuration

The web interface is built from Svelte sources, which requires:

* `nodejs`
* `npm`

However the source code ships with a compiled UI (pure JavaScript), so nodejs and npm is not strictly required.

(On Debian/Ubuntu the package names are given in parentheses.)

==== Building

{empty} +

Download the source from the Download page and extract it, e.g.

`tar -xzvf mhuxd-0.90.tar.gz`

{empty} +

NOTE: If you cloned the source from GitHub instead, you also need the packages
`autoconf` and `automake` and must run `./autogen.sh` once before `./configure`.

{empty} +

Change into the source directory and perform:

`./configure`

`make`

`make install`

This will install everything into /usr/local. If you want everything in a single folder you can use the --prefix option of configure:

`./configure --prefix=/usr/local/mhuxd`

`make`

`make install`

Make sure that the required kernel modules are loaded:

`modprobe ftdi_sio`

`modprobe cuse`

Start mhuxd on the command line:

`sudo /usr/local/sbin/mhuxd`

NOTE: mhuxd does not need to run as root, but it needs read/write access to
`/dev/cuse`, which is typically owned by root.
